# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb-dev-hello',
                'doc_host': 'https://ofemeteng.github.io',
                'git_url': 'https://github.com/ofemeteng/nb-dev-hello',
                'lib_path': 'nb_dev_hello'},
  'syms': {'nb_dev_hello.core': {'nb_dev_hello.core.foo': ('core.html#foo', 'nb_dev_hello/core.py')}}}
